export * from "./Bath"
export * from "./Warwick"
export * from "./Birmingham"
export * from "./StAndrews"
export * from "./Nottingham"
export * from "./Aberdeen"
export * from "./KCL"
export * from "./Surrey"
export * from "./York"
export * from "./Cardiff"
export * from "./Newcastle"
export * from "./Imperial"
export * from "./Aston"
export * from "./Essex"
export * from "./Kent"
export * from "./Leicester"
export * from "./Lincoln"
export * from "./Northumbria"
export * from "./QueensBelfast"
export * from "./Reading"
export * from "./SOAS"
export * from "./Sheffield"
export * from "./Swansea"
export * from "./Sussex"
export * from "./Southampton"
export * from "./Stirling"
export * from "./Bristol"
export * from "./Buckinghamshire"
export * from "./CityUOL"
export * from "./Coventry"
export * from "./EdgeHill"
export * from "./Keele"
export * from "./Liverpool"
export * from "./LiverpoolHope"
export * from "./Manchester"
export * from "./ManchesterMet"
export * from "./NottinghamTrent"
export * from "./Portsmouth"
export * from "./Staffordshire"
export * from "./Ulster"
export * from "./ArtsLondon"
export * from "./ArtsuniversityBournemouth"
export * from "./Bradford"
export * from "./CollegeLondon"
export * from "./De Montfort"
export * from "./Dundee"
export * from "./EastAnglia"
export * from "./Edinburgh"
export * from "./HeriotWatt"
export * from "./Huddersfield"
export * from "./LiverpoolJohnMoores"
export * from "./LondonSchoolofEconomics"
export * from "./Oxford"
export * from "./OxfordBrookes"
export * from "./Queen Margaret"
export * from "./QueenMary"
export * from "./RoyalHolloway"
export * from "./StGeorge's"
export * from "./Strathclyde"
export * from "./Cambridge"
export * from "./Hertfordshire"
export * from "./CentralLancaster"
export * from "./GlasgowCaledonian"
export * from "./Plymouth"
export * from "./Leeds Arts"
export * from "./London South Bank"
export * from "./Middlesex"
export * from "./Bangor"
export * from "./Bath spa"
export * from "./Birmingham City"
export * from "./Cardiff Metropolitan"
export * from "./CentralLancaster"
export * from "./Chichester"
export * from "./Edinburgh Napier"
export * from "./Falmouth"
export * from "./GlasgowCaledonian"
export * from "./Greenwich"
export * from "./Hertfordshire"
export * from "./Hull"
export * from "./Kingston"
export * from "./Leeds Arts"
export * from "./London South Bank"
export * from "./Middlesex"
export * from "./Plymouth"
export * from "./Robert Gordon"
export * from "./Salford"
export * from "./SheffieldHallam"
export * from "./St Mary's Twickenham"
export * from "./West London"
export * from "./Westminster"
export * from "./Cardiff Metropolitan"
export * from "./St Mary's Twickenham"
export * from "./Leeds Arts"
export * from "./Derby"
export * from "./Gloucestershire"
export * from "./Wales Trinity Saint David"
export * from "./Solent"
export * from "./Winchester"
export * from "./Sunderland"
export * from "./Buckingham"
export * from "./Northhampton"
export * from "./York St John"
export * from "./Leeds Trinity"
export * from "./South Wales"
export * from "./Brighton"
export * from "./Buckinghamshire"
export * from "./East London"
export * from "./Canterbury Christ Church"
export * from "./Anglia Ruskin"
export * from "./Bishop Grosseteste"
export * from "./Cumbria"
export * from "./Leeds Beckett"
export * from "./Bedfordshire"
export * from "./Royal Agricultural University"
export * from "./Wolverhampton"
export * from "./Newman"
export * from "./Plymouth Marjon"
export * from "./Suffolk"
export * from "./Ravensbourne"
export * from "./Chester"
export * from "./Brunel"
export * from "./Bournemouth"
export * from "./Aberystwyth"
export * from "./Goldsmiths"

